Repository mozilla-services/autopush, pull requests merged in 2018-04, with the labels that each got.

#1168 chore: tag 1.43.0
  CHANGELOG.md
  autopush/__init__.py
Labels: in progress

#1169 feat: refactor client to remove duplicate logic
  autopush_rs/src/client.rs
Labels: in progress

#1171 feat: update dependencies
  autopush_rs/Cargo.lock
  autopush_rs/Cargo.toml
  requirements.txt
Labels: enhancement, in progress, p1

#1174 fix: wrong toggling of autopush_rs's json_logging
  autopush/tests/test_log_check.py
  autopush/tests/test_rs_integration.py
  autopush/web/log_check.py
  autopush_rs/__init__.py
Labels: bug, in progress, p1

#1176 chore: tag 1.44.0
  CHANGELOG.md
  autopush/__init__.py
Labels: in progress

#1175 feat: add a crit log_check to autopush_rs
  autopush_rs/src/server/dispatch.rs
  autopush_rs/src/server/mod.rs
Labels: enhancement, in progress, p1

#1178 feat: fix asserts on client dis/connect and convert inc call to rust
  .travis.yml
  automock/boto.cfg
  autopush/tests/test_webpush_server.py
  autopush/webpush_server.py
  autopush_rs/Cargo.lock
  autopush_rs/Cargo.toml
  autopush_rs/src/call.rs
  autopush_rs/src/client.rs
  autopush_rs/src/lib.rs
  autopush_rs/src/protocol.rs
  autopush_rs/src/server/mod.rs
  autopush_rs/src/util/ddb_helpers.rs
  autopush_rs/src/util/mod.rs
Labels: in progress

#1182 feat: refactor client state machine
  autopush_rs/Cargo.lock
  autopush_rs/Cargo.toml
  autopush_rs/src/client.rs
  autopush_rs/src/lib.rs
  autopush_rs/src/protocol.rs
  autopush_rs/src/server/mod.rs
  autopush_rs/src/util/megaphone.rs
Labels: in progress

#1186 fix: disable the logger guard for now
  autopush_rs/src/server/mod.rs
  autopush_rs/src/util/mod.rs
Labels: bug, in progress

#1187 fix: return simple uaid to hello
  autopush/tests/test_integration.py
  autopush_rs/src/client.rs
Labels: in progress

#1191 feat: use chrono epoch times instead of monotonic time
  autopush_rs/Cargo.toml
  autopush_rs/src/client.rs
  autopush_rs/src/util/mod.rs
Labels: in progress

#1193 chore: tag 1.45.0
  CHANGELOG.md
  autopush/__init__.py
Labels: in progress
