Repository mozilla-services/autopush, pull requests merged in 2018-05, with the labels that each got.

#1197 bug: sync endpoint and connection settings during integration testing
  autopush/tests/test_rs_integration.py
Labels: in progress

#1202 feat: port check storage command into Rust
  autopush/tests/test_rs_integration.py
  autopush/tests/test_webpush_server.py
  autopush/webpush_server.py
  autopush_rs/Cargo.lock
  autopush_rs/Cargo.toml
  autopush_rs/src/call.rs
  autopush_rs/src/client.rs
  autopush_rs/src/errors.rs
  autopush_rs/src/lib.rs
  autopush_rs/src/protocol.rs
  autopush_rs/src/server/mod.rs
  autopush_rs/src/util/ddb_helpers.rs
Labels: in progress

#1203 rustfmt all the rust
  autopush_rs/src/call.rs
  autopush_rs/src/client.rs
  autopush_rs/src/http.rs
  autopush_rs/src/lib.rs
  autopush_rs/src/protocol.rs
  autopush_rs/src/rt.rs
  autopush_rs/src/server/mod.rs
  autopush_rs/src/server/tls.rs
  autopush_rs/src/util/autojson.rs
  autopush_rs/src/util/megaphone.rs
  autopush_rs/src/util/rc.rs
  autopush_rs/src/util/send_all.rs
Labels: in progress

#1212 bug: Remove unused "expiry" from Router table
  autopush/db.py
Labels: in progress

#1214 feat: hardcode autopush_rs's AWS creds in local dynamodb mode
  .travis.yml
  Dockerfile.automock
  automock/boto.cfg
  automock/supervisord.conf
  autopush_rs/Cargo.lock
  autopush_rs/Cargo.toml
  autopush_rs/src/lib.rs
  autopush_rs/src/util/ddb_helpers.rs
  boto-compose.cfg
  docker-compose.yml
Labels: enhancement, in progress, p1

#1213 fix: don't save legacy messages from the Rust node
  autopush/webpush_server.py
  autopush_rs/src/client.rs
Labels: in progress

#1215 fix: properly catch a null value passed to register
  autopush/tests/test_websocket.py
  autopush/websocket.py
Labels: in progress

#1216 fix: endpoint now returns a JSON-based 404 for all 404's
  autopush/http.py
  autopush/tests/test_integration.py
  autopush/web/base.py
Labels: in progress

#1219 refactor: some cleanup for #1202
  autopush_rs/src/util/ddb_helpers.rs
Labels: in progress

#1220 feat: port hello command to Rust
  autopush/db.py
  autopush/tests/test_rs_integration.py
  autopush/tests/test_webpush_server.py
  autopush/web/registration.py
  autopush/webpush_server.py
  autopush/websocket.py
  autopush_rs/Cargo.lock
  autopush_rs/Cargo.toml
  autopush_rs/__init__.py
  autopush_rs/src/call.rs
  autopush_rs/src/client.rs
  autopush_rs/src/lib.rs
  autopush_rs/src/server/mod.rs
  autopush_rs/src/util/ddb_helpers.rs
  autopush_rs/src/util/mod.rs
  autopush_rs/src/util/timing.rs
Labels: in progress

#1222 feat: port register command to Rust
  .travis.yml
  autopush/tests/test_integration.py
  autopush/tests/test_rs_integration.py
  autopush/tests/test_webpush_server.py
  autopush/webpush_server.py
  autopush_rs/Cargo.lock
  autopush_rs/Cargo.toml
  autopush_rs/__init__.py
  autopush_rs/src/call.rs
  autopush_rs/src/client.rs
  autopush_rs/src/lib.rs
  autopush_rs/src/server/mod.rs
  autopush_rs/src/util/ddb_helpers.rs
Labels: in progress

#1223 feat: port drop user command to Rust
  autopush/tests/test_webpush_server.py
  autopush/webpush_server.py
  autopush_rs/src/call.rs
  autopush_rs/src/client.rs
  autopush_rs/src/util/ddb_helpers.rs
Labels: in progress

#1226 feat: switch from snaek to milksnake
  .travis.yml
  Dockerfile
  Dockerfile.python27
  autopush_rs/Cargo.lock
  autopush_rs/Cargo.toml
  autopush_rs/build.rs
  autopush_rs/src/call.rs
  autopush_rs/src/queue.rs
  autopush_rs/src/server/mod.rs
  requirements.txt
  setup.py
  tox.ini
Labels: enhancement

#1228 fix: reject unhyphenated channelIDs from register
  autopush_rs/src/client.rs
  autopush_rs/src/protocol.rs
Labels: bug, in progress, p1

#1234 feat: port store messages command to Rust
  autopush/tests/test_rs_integration.py
  autopush/tests/test_webpush_server.py
  autopush/webpush_server.py
  autopush_rs/src/call.rs
  autopush_rs/src/client.rs
  autopush_rs/src/util/ddb_helpers.rs
Labels: in progress

#1236 fix: let the build continue to rustc on cbindgen failures
  autopush_rs/build.rs
Labels: bug, p1

#1233 fix: properly set record expiration
  autopush/db.py
  autopush/websocket.py
  tox.ini
Labels: in progress

#1245 refactor: minor cleanup, then impl trait and box killing
  autopush_rs/src/db/commands.rs
  autopush_rs/src/db/mod.rs
Labels: in progress

#1244 feat: add Rust + Python mixed integration tests
  autopush/tests/test_integration.py
  autopush/tests/test_rs_integration.py
Labels: in progress

#1246 refactor: more impl trait, etc
  autopush_rs/src/client.rs
  autopush_rs/src/db/commands.rs
  autopush_rs/src/db/mod.rs
Labels: in progress

#1248 fix: shrink the Docker build
  Dockerfile
  Dockerfile.python27
  autopush/tests/test_rs_integration.py
Labels: bug, in progress, p1

#1250 fix: ensure consistent_read on fetch messages fns
  autopush_rs/src/db/commands.rs
Labels: bug, p1

#1254 fix: actually pass thru $WITH_RUST
  Dockerfile
  Dockerfile.python27
Labels: Operational, bug, p1

#1257 feat: switch to slog-mozlog-json/mozsvc-common for logging
  .travis.yml
  Cargo.lock
  autopush/tests/test_rs_integration.py
  autopush_rs/Cargo.toml
  autopush_rs/src/client.rs
  autopush_rs/src/lib.rs
  autopush_rs/src/logging.rs
  autopush_rs/src/server/mod.rs
  autopush_rs/src/settings.rs
  autopush_rs/src/util/autojson.rs
  autopush_rs/src/util/aws.rs
  autopush_rs/src/util/mod.rs
Labels: enhancement, p1
