Repository mozilla-services/autopush, pull requests merged in 2018-08, with the labels that each got.

#1280 chore: tag 1.49.2
  CHANGELOG.md
  autopush/__init__.py
Labels: in progress

#1282 feat: improve endpoint_diagnostic tool and documents
  autopush/diagnostic_cli.py
  autopush/tests/test_diagnostic_cli.py
  docs/testing.rst
Labels: in progress

#1283 fix: disallow negative ttls
  autopush/tests/test_integration.py
  autopush/web/webpush.py
Labels: bug, in progress, p1

#1284 chore: tag 1.50.0
  CHANGELOG.md
  autopush/__init__.py
Labels: in progress

#1286 fix: timeout gcm calls
  autopush/router/gcm.py
Labels: bug, in progress, p1

#1287 chore: tag 1.50.1
  CHANGELOG.md
  autopush/__init__.py
Labels: in progress

#1289 feat: upgrade to pypy6 for debug symbols
  Dockerfile
  autopush/memusage.py
  autopush/router/gcm.py
  autopush/tests/test_integration.py
  docs/http.rst
Labels: enhancement, in progress

#1290 feat: add ADM support
  autopush/config.py
  autopush/main_argparse.py
  autopush/router/__init__.py
  autopush/router/adm.py
  autopush/tests/test_integration.py
  autopush/tests/test_z_main.py
  autopush/web/registration.py
  autopush/web/webpush.py
  configs/autopush_endpoint.ini.sample
  docs/adm.rst
  docs/glossary.rst
  docs/install.rst
Labels: in progress
