Repository mozilla-services/autopush, pull requests merged in 2018-02, with the labels that each got.

#1128 feat: update python dependencies to the latest versions
  Makefile
  requirements.txt
  tox.ini
Labels: enhancement, in progress

#1131 fix: make autopush_rs's ctrl-c work gracefully
  autopush/main.py
  autopush/tests/test_rs_integration.py
  autopush/webpush_server.py
  autopush_rs/src/errors.rs
  autopush_rs/src/server/mod.rs
Labels: bug, in progress

#1135 feat: drain pending notifications from the client rx queue
  autopush_rs/src/client.rs
Labels: in progress

#1136 fix: reverse our filled in stack trace order
  autopush/logging.py
  autopush/tests/test_logging.py
Labels: bug, in progress

#1137 fix: bind autopush_rs to all interfaces to match python
  autopush/config.py
  autopush/db.py
  autopush/logging.py
  autopush/main.py
  autopush/memusage.py
  autopush/metrics.py
  autopush/tests/test_utils.py
  autopush/utils.py
  autopush/webpush_server.py
  autopush_rs/Cargo.lock
  autopush_rs/Cargo.toml
  autopush_rs/__init__.py
  autopush_rs/src/lib.rs
  autopush_rs/src/server/mod.rs
  autopush_rs/src/util/aws.rs
  autopush_rs/src/util/mod.rs
Labels: bug, in progress

#1130 bug: Silence remaining nuisance alarms
  autopush/router/apns2.py
  autopush/router/apnsrouter.py
  autopush/tests/test_db.py
  autopush/tests/test_router.py
  autopush/tests/test_web_base.py
  autopush/tests/test_websocket.py
  autopush/web/base.py
  autopush/websocket.py
Labels: in progress
