Repository mozilla-services/autopush, pull requests merged in 2019-04, with the labels that each got.

#1328 chore: bump to latest pypy
  .travis.yml
  Dockerfile
Labels: bug, in progress

#1329 chore: update urllib
  requirements.txt
Labels: enhancement, in progress

#1331 bug: Fix all_channels to match registration UAID format
  autopush/db.py
  autopush/tests/test_db.py
Labels: in progress

#1332 fix: handle TypeErrors too
  autopush/tests/test_integration.py
  autopush/web/webpush.py
Labels: bug, in progress, p1

#1333 chore: tag 1.53.3
  CHANGELOG.md
  autopush/__init__.py
Labels: in progress
